name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - black
  - bokeh
  - flake8
  - cudatoolkit=10.1
  - pytorch
  - easydict
  - ffmpeg-python
  - ipywidgets
  - jupyterlab
  - jupyterlab_code_formatter
  - numpy
  - opencv
  - pandas
  - python=3.8
  - pip
  - pre-commit
  - pydantic
  - pylint
  - scikit-image
  - vim
